/**
 * 추천용 장절 메타데이터 시드.
 * 실행: `npx tsx lib/db/seed-verses.ts`
 *
 * 절대 규칙: 개역개정 원문(본문)은 저장하지 않는다.
 * summary 는 사람이 쓴 한 줄 요지이며 성경 본문이 아니다.
 *
 * TODO: 개역개정 원문 직접 저장/노출 전 대한성서공회 저작권 검토 필요
 */

import { config } from "dotenv";
config({ path: ".env.local" });

import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import { sql } from "drizzle-orm";
import { verses } from "./schema";

if (!process.env.DATABASE_URL) {
  console.error("❌ DATABASE_URL 이 비어 있습니다. .env.local 을 확인하세요.");
  process.exit(1);
}

const client = postgres(process.env.DATABASE_URL, { prepare: false });
const db = drizzle(client);

// 어떤 DB 에 붙는지 시각 확인
try {
  const u = new URL(process.env.DATABASE_URL.replace(/^postgresql:/, "http:"));
  console.log(`[seed-verses] target = ${u.host}`);
} catch {
  // URL 파싱 실패는 무시 — 시드 진행 자체에는 영향 없음
}

type Seed = {
  referenceKo: string;
  bookAbbrEn: string;
  chapter: number;
  verseStart: number;
  verseEnd?: number;
  themes: string[];
  situationTags: string[];
  emotionTags: string[];
  summary?: string;
  weight?: number;
  isGeneric?: boolean;
};

const link = (book: string, ch: number, v: number) =>
  `https://bible.bskorea.or.kr/bible/NKRV/${book}.${ch}.${v}`;

const SEEDS: Seed[] = [
  // ─── 게으름 / 생활질서 무너짐 ────────────────────────────────────
  {
    referenceKo: "잠언 24:30-34",
    bookAbbrEn: "PRO",
    chapter: 24,
    verseStart: 30,
    verseEnd: 34,
    themes: ["게으름", "생활질서"],
    situationTags: ["생활질서무너짐", "자기방임"],
    emotionTags: ["무기력"],
    summary: "게으른 자의 밭을 보며 작은 나태가 쌓이는 결과를 생각하게 한다.",
    weight: 90,
  },
  {
    referenceKo: "잠언 6:6-11",
    bookAbbrEn: "PRO",
    chapter: 6,
    verseStart: 6,
    verseEnd: 11,
    themes: ["게으름", "성실"],
    situationTags: ["자기방임", "미루는습관"],
    emotionTags: ["무기력"],
    summary: "개미의 부지런함을 통해 게으름의 결과를 돌아보게 한다.",
    weight: 85,
  },
  {
    referenceKo: "잠언 13:4",
    bookAbbrEn: "PRO",
    chapter: 13,
    verseStart: 4,
    themes: ["게으름", "성실"],
    situationTags: ["자기방임"],
    emotionTags: ["무기력"],
    summary: "게으른 자의 마음은 원하나 얻지 못한다.",
    weight: 70,
  },
  {
    referenceKo: "전도서 9:10",
    bookAbbrEn: "ECC",
    chapter: 9,
    verseStart: 10,
    themes: ["성실", "책임"],
    situationTags: ["작은책임회복"],
    emotionTags: [],
    summary: "손이 일을 얻는 대로 힘을 다하여 할지어다.",
    weight: 75,
  },
  {
    referenceKo: "골로새서 3:23",
    bookAbbrEn: "COL",
    chapter: 3,
    verseStart: 23,
    themes: ["성실", "일"],
    situationTags: ["일의의미", "회사어려움"],
    emotionTags: [],
    summary: "사람에게 하듯 하지 말고 주께 하듯 하라.",
    weight: 70,
  },

  // ─── 불안 / 답답함 / 기도 결단 ────────────────────────────────────
  {
    referenceKo: "빌립보서 4:6-7",
    bookAbbrEn: "PHP",
    chapter: 4,
    verseStart: 6,
    verseEnd: 7,
    themes: ["기도", "평안"],
    situationTags: ["기도결단"],
    emotionTags: ["불안", "답답함"],
    summary: "염려 대신 기도와 감사로 아뢰라.",
    weight: 95,
  },
  {
    referenceKo: "베드로전서 5:7",
    bookAbbrEn: "1PE",
    chapter: 5,
    verseStart: 7,
    themes: ["맡김", "기도"],
    situationTags: ["기도결단"],
    emotionTags: ["불안", "염려"],
    summary: "너희 염려를 다 주께 맡기라.",
    weight: 85,
  },
  {
    referenceKo: "시편 55:22",
    bookAbbrEn: "PSA",
    chapter: 55,
    verseStart: 22,
    themes: ["맡김"],
    situationTags: ["기도결단"],
    emotionTags: ["불안", "답답함"],
    summary: "네 짐을 여호와께 맡기라.",
    weight: 80,
  },
  {
    referenceKo: "마태복음 6:33-34",
    bookAbbrEn: "MAT",
    chapter: 6,
    verseStart: 33,
    verseEnd: 34,
    themes: ["기도", "우선순위"],
    situationTags: ["기도결단", "염려"],
    emotionTags: ["불안"],
    summary: "먼저 그의 나라와 의를 구하라.",
    weight: 80,
  },
  {
    referenceKo: "이사야 41:10",
    bookAbbrEn: "ISA",
    chapter: 41,
    verseStart: 10,
    themes: ["담대함", "함께하심"],
    situationTags: ["회사어려움"],
    emotionTags: ["두려움", "불안"],
    summary: "두려워 말라 내가 너와 함께 함이라.",
    weight: 85,
    isGeneric: true,
  },
  {
    referenceKo: "시편 27:1",
    bookAbbrEn: "PSA",
    chapter: 27,
    verseStart: 1,
    themes: ["담대함"],
    situationTags: [],
    emotionTags: ["두려움"],
    summary: "여호와는 나의 빛이요 나의 구원이시니.",
    weight: 60,
    isGeneric: true,
  },
  {
    referenceKo: "시편 46:1-3",
    bookAbbrEn: "PSA",
    chapter: 46,
    verseStart: 1,
    verseEnd: 3,
    themes: ["피난처"],
    situationTags: ["삶의흔들림"],
    emotionTags: ["불안", "두려움"],
    summary: "하나님은 우리의 피난처시요 힘이시니.",
    weight: 65,
  },
  {
    referenceKo: "시편 42:5",
    bookAbbrEn: "PSA",
    chapter: 42,
    verseStart: 5,
    themes: ["소망"],
    situationTags: [],
    emotionTags: ["우울", "답답함"],
    summary: "내 영혼아 네가 어찌하여 낙심하며.",
    weight: 60,
  },

  // ─── 주님의 뜻 / 맡김 / 내 계획 내려놓기 ──────────────────────────
  {
    referenceKo: "잠언 16:3",
    bookAbbrEn: "PRO",
    chapter: 16,
    verseStart: 3,
    themes: ["맡김", "하나님의뜻"],
    situationTags: ["계획맡김"],
    emotionTags: [],
    summary: "너의 행사를 여호와께 맡기라.",
    weight: 85,
  },
  {
    referenceKo: "잠언 16:9",
    bookAbbrEn: "PRO",
    chapter: 16,
    verseStart: 9,
    themes: ["하나님의뜻"],
    situationTags: ["계획맡김"],
    emotionTags: [],
    summary: "사람의 마음으로 자기 길을 계획할지라도 걸음을 인도하시는 이는 여호와시니라.",
    weight: 80,
  },
  {
    referenceKo: "잠언 3:5-6",
    bookAbbrEn: "PRO",
    chapter: 3,
    verseStart: 5,
    verseEnd: 6,
    themes: ["신뢰", "하나님의뜻"],
    situationTags: ["계획맡김"],
    emotionTags: [],
    summary: "네 명철을 의지하지 말고 여호와를 신뢰하라.",
    weight: 85,
    isGeneric: true,
  },
  {
    referenceKo: "야고보서 4:13-15",
    bookAbbrEn: "JAS",
    chapter: 4,
    verseStart: 13,
    verseEnd: 15,
    themes: ["하나님의뜻", "겸손"],
    situationTags: ["계획맡김"],
    emotionTags: [],
    summary: "주의 뜻이면 우리가 살기도 하고 이것이나 저것을 하리라.",
    weight: 85,
  },
  {
    referenceKo: "로마서 8:28",
    bookAbbrEn: "ROM",
    chapter: 8,
    verseStart: 28,
    themes: ["하나님의뜻"],
    situationTags: [],
    emotionTags: ["답답함"],
    summary: "모든 것이 합력하여 선을 이루느니라.",
    weight: 55,
    isGeneric: true,
  },
  {
    referenceKo: "예레미야 29:11",
    bookAbbrEn: "JER",
    chapter: 29,
    verseStart: 11,
    themes: ["하나님의뜻", "소망"],
    situationTags: [],
    emotionTags: ["염려"],
    summary: "여호와의 말씀이니라 너희를 향한 나의 생각은 평안이요.",
    weight: 50,
    isGeneric: true,
  },

  // ─── 회사/일터의 어려움 ─────────────────────────────────────────
  {
    referenceKo: "여호수아 1:9",
    bookAbbrEn: "JOS",
    chapter: 1,
    verseStart: 9,
    themes: ["담대함", "함께하심"],
    situationTags: ["회사어려움", "새로운도전"],
    emotionTags: ["두려움"],
    summary: "강하고 담대하라 네 하나님 여호와가 너와 함께하느니라.",
    weight: 80,
    isGeneric: true,
  },
  {
    referenceKo: "느헤미야 8:10",
    bookAbbrEn: "NEH",
    chapter: 8,
    verseStart: 10,
    themes: ["기쁨"],
    situationTags: ["회사어려움"],
    emotionTags: ["무기력"],
    summary: "여호와로 인하여 기뻐하는 것이 너희의 힘이니라.",
    weight: 65,
  },
  {
    referenceKo: "출애굽기 14:14",
    bookAbbrEn: "EXO",
    chapter: 14,
    verseStart: 14,
    themes: ["맡김"],
    situationTags: ["회사어려움", "대인관계"],
    emotionTags: ["답답함"],
    summary: "여호와께서 너희를 위하여 싸우시리니 너희는 가만히 있을지니라.",
    weight: 70,
  },
  {
    referenceKo: "이사야 40:29-31",
    bookAbbrEn: "ISA",
    chapter: 40,
    verseStart: 29,
    verseEnd: 31,
    themes: ["회복", "소망"],
    situationTags: ["번아웃", "회사어려움"],
    emotionTags: ["무기력"],
    summary: "여호와를 앙망하는 자는 새 힘을 얻으리니.",
    weight: 80,
  },
  {
    referenceKo: "시편 23:1-4",
    bookAbbrEn: "PSA",
    chapter: 23,
    verseStart: 1,
    verseEnd: 4,
    themes: ["인도하심"],
    situationTags: [],
    emotionTags: ["두려움"],
    summary: "여호와는 나의 목자시니 내게 부족함이 없으리로다.",
    weight: 55,
    isGeneric: true,
  },

  // ─── 감사 / 기쁨 ───────────────────────────────────────────────
  {
    referenceKo: "데살로니가전서 5:16-18",
    bookAbbrEn: "1TH",
    chapter: 5,
    verseStart: 16,
    verseEnd: 18,
    themes: ["감사", "기도"],
    situationTags: ["감사결단"],
    emotionTags: [],
    summary: "항상 기뻐하라 쉬지 말고 기도하라 범사에 감사하라.",
    weight: 80,
  },
  {
    referenceKo: "시편 103:1-5",
    bookAbbrEn: "PSA",
    chapter: 103,
    verseStart: 1,
    verseEnd: 5,
    themes: ["감사"],
    situationTags: ["감사결단"],
    emotionTags: [],
    summary: "내 영혼아 여호와를 송축하라.",
    weight: 65,
  },
  {
    referenceKo: "시편 118:24",
    bookAbbrEn: "PSA",
    chapter: 118,
    verseStart: 24,
    themes: ["감사", "기쁨"],
    situationTags: [],
    emotionTags: [],
    summary: "이 날은 여호와께서 정하신 것이라.",
    weight: 50,
  },

  // ─── 회개 / 자기성찰 ───────────────────────────────────────────
  {
    referenceKo: "시편 51:10-12",
    bookAbbrEn: "PSA",
    chapter: 51,
    verseStart: 10,
    verseEnd: 12,
    themes: ["회개", "정결"],
    situationTags: ["자기성찰"],
    emotionTags: ["죄책감"],
    summary: "하나님이여 내 속에 정한 마음을 창조하시고.",
    weight: 80,
  },
  {
    referenceKo: "시편 139:23-24",
    bookAbbrEn: "PSA",
    chapter: 139,
    verseStart: 23,
    verseEnd: 24,
    themes: ["회개", "자기성찰"],
    situationTags: ["자기성찰"],
    emotionTags: [],
    summary: "하나님이여 나를 살피사 내 마음을 아시며.",
    weight: 75,
  },
  {
    referenceKo: "요한1서 1:9",
    bookAbbrEn: "1JN",
    chapter: 1,
    verseStart: 9,
    themes: ["회개", "용서"],
    situationTags: ["자기성찰"],
    emotionTags: ["죄책감"],
    summary: "우리가 우리 죄를 자백하면.",
    weight: 70,
  },
  {
    referenceKo: "이사야 55:6-7",
    bookAbbrEn: "ISA",
    chapter: 55,
    verseStart: 6,
    verseEnd: 7,
    themes: ["회개"],
    situationTags: ["돌이킴"],
    emotionTags: ["죄책감"],
    summary: "여호와를 만날 만한 때에 찾으라.",
    weight: 65,
  },
  {
    referenceKo: "호세아 6:1",
    bookAbbrEn: "HOS",
    chapter: 6,
    verseStart: 1,
    themes: ["회개"],
    situationTags: ["돌이킴"],
    emotionTags: [],
    summary: "오라 우리가 여호와께로 돌아가자.",
    weight: 55,
  },

  // ─── 순종 / 결단 ───────────────────────────────────────────────
  {
    referenceKo: "로마서 12:1-2",
    bookAbbrEn: "ROM",
    chapter: 12,
    verseStart: 1,
    verseEnd: 2,
    themes: ["헌신", "순종"],
    situationTags: ["결단"],
    emotionTags: [],
    summary: "너희 몸을 하나님이 기뻐하시는 산 제물로 드리라.",
    weight: 80,
  },
  {
    referenceKo: "마태복음 16:24",
    bookAbbrEn: "MAT",
    chapter: 16,
    verseStart: 24,
    themes: ["자기부인", "순종"],
    situationTags: ["결단"],
    emotionTags: [],
    summary: "누구든지 나를 따라오려거든 자기를 부인하고.",
    weight: 70,
  },
  {
    referenceKo: "누가복음 9:62",
    bookAbbrEn: "LUK",
    chapter: 9,
    verseStart: 62,
    themes: ["순종", "결단"],
    situationTags: ["결단"],
    emotionTags: [],
    summary: "손에 쟁기를 잡고 뒤를 돌아보는 자는.",
    weight: 60,
  },
  {
    referenceKo: "갈라디아서 6:9",
    bookAbbrEn: "GAL",
    chapter: 6,
    verseStart: 9,
    themes: ["인내", "성실"],
    situationTags: ["지침"],
    emotionTags: ["무기력"],
    summary: "선을 행하되 낙심하지 말지니.",
    weight: 70,
  },
  {
    referenceKo: "히브리서 12:1-2",
    bookAbbrEn: "HEB",
    chapter: 12,
    verseStart: 1,
    verseEnd: 2,
    themes: ["인내", "믿음의경주"],
    situationTags: ["지침"],
    emotionTags: ["무기력"],
    summary: "우리 앞에 당한 경주를 인내로써 경주하며.",
    weight: 70,
  },

  // ─── 외로움 / 낙심 ─────────────────────────────────────────────
  {
    referenceKo: "시편 34:18",
    bookAbbrEn: "PSA",
    chapter: 34,
    verseStart: 18,
    themes: ["위로"],
    situationTags: [],
    emotionTags: ["슬픔", "외로움"],
    summary: "여호와는 마음이 상한 자를 가까이 하시고.",
    weight: 70,
  },
  {
    referenceKo: "시편 73:23-26",
    bookAbbrEn: "PSA",
    chapter: 73,
    verseStart: 23,
    verseEnd: 26,
    themes: ["함께하심"],
    situationTags: [],
    emotionTags: ["외로움"],
    summary: "내가 항상 주와 함께 하니 주께서 내 오른손을 붙드셨나이다.",
    weight: 60,
  },
  {
    referenceKo: "마태복음 11:28-30",
    bookAbbrEn: "MAT",
    chapter: 11,
    verseStart: 28,
    verseEnd: 30,
    themes: ["쉼", "위로"],
    situationTags: ["번아웃"],
    emotionTags: ["무기력", "지침"],
    summary: "수고하고 무거운 짐 진 자들아 다 내게로 오라.",
    weight: 85,
    isGeneric: true,
  },
  {
    referenceKo: "요한복음 14:27",
    bookAbbrEn: "JHN",
    chapter: 14,
    verseStart: 27,
    themes: ["평안"],
    situationTags: [],
    emotionTags: ["불안"],
    summary: "평안을 너희에게 끼치노니 곧 나의 평안을 너희에게 주노라.",
    weight: 60,
    isGeneric: true,
  },

  // ─── 관계 / 용서 ───────────────────────────────────────────────
  {
    referenceKo: "에베소서 4:31-32",
    bookAbbrEn: "EPH",
    chapter: 4,
    verseStart: 31,
    verseEnd: 32,
    themes: ["용서", "관계"],
    situationTags: ["대인관계"],
    emotionTags: ["분노"],
    summary: "서로 친절하게 하며 불쌍히 여기며 서로 용서하기를.",
    weight: 70,
  },
  {
    referenceKo: "마태복음 6:14-15",
    bookAbbrEn: "MAT",
    chapter: 6,
    verseStart: 14,
    verseEnd: 15,
    themes: ["용서"],
    situationTags: ["대인관계"],
    emotionTags: ["분노"],
    summary: "너희가 사람의 잘못을 용서하면.",
    weight: 60,
  },
  {
    referenceKo: "로마서 12:17-18",
    bookAbbrEn: "ROM",
    chapter: 12,
    verseStart: 17,
    verseEnd: 18,
    themes: ["관계", "화평"],
    situationTags: ["대인관계"],
    emotionTags: ["분노"],
    summary: "할 수 있거든 너희로서는 모든 사람과 더불어 화목하라.",
    weight: 60,
  },

  // ─── 물질 / 염려 / 만족 ───────────────────────────────────────
  {
    referenceKo: "빌립보서 4:11-13",
    bookAbbrEn: "PHP",
    chapter: 4,
    verseStart: 11,
    verseEnd: 13,
    themes: ["자족"],
    situationTags: ["재정염려"],
    emotionTags: ["불안"],
    summary: "어떠한 형편에든지 나는 자족하기를 배웠노니.",
    weight: 70,
  },
  {
    referenceKo: "히브리서 13:5",
    bookAbbrEn: "HEB",
    chapter: 13,
    verseStart: 5,
    themes: ["자족", "함께하심"],
    situationTags: ["재정염려"],
    emotionTags: [],
    summary: "돈을 사랑하지 말고 있는 바를 족한 줄로 알라.",
    weight: 65,
  },
  {
    referenceKo: "마태복음 6:25-27",
    bookAbbrEn: "MAT",
    chapter: 6,
    verseStart: 25,
    verseEnd: 27,
    themes: ["염려"],
    situationTags: ["재정염려", "염려"],
    emotionTags: ["불안"],
    summary: "목숨을 위하여 무엇을 먹을까 무엇을 마실까 염려하지 말라.",
    weight: 70,
  },

  // ─── 기다림 / 인내 ─────────────────────────────────────────────
  {
    referenceKo: "시편 27:14",
    bookAbbrEn: "PSA",
    chapter: 27,
    verseStart: 14,
    themes: ["기다림"],
    situationTags: ["하나님의때"],
    emotionTags: ["답답함"],
    summary: "너는 여호와를 기다릴지어다.",
    weight: 65,
  },
  {
    referenceKo: "시편 37:7-8",
    bookAbbrEn: "PSA",
    chapter: 37,
    verseStart: 7,
    verseEnd: 8,
    themes: ["기다림", "맡김"],
    situationTags: ["하나님의때"],
    emotionTags: ["분노", "답답함"],
    summary: "여호와 앞에 잠잠하고 참고 기다리라.",
    weight: 65,
  },
  {
    referenceKo: "예레미야애가 3:22-26",
    bookAbbrEn: "LAM",
    chapter: 3,
    verseStart: 22,
    verseEnd: 26,
    themes: ["기다림", "긍휼"],
    situationTags: ["하나님의때"],
    emotionTags: ["슬픔"],
    summary: "여호와의 인자와 긍휼이 무궁하시므로.",
    weight: 60,
  },

  // ─── 말씀 / 기도 생활 회복 ────────────────────────────────────
  {
    referenceKo: "시편 1:1-3",
    bookAbbrEn: "PSA",
    chapter: 1,
    verseStart: 1,
    verseEnd: 3,
    themes: ["말씀", "복"],
    situationTags: ["말씀묵상회복"],
    emotionTags: [],
    summary: "복 있는 사람은 여호와의 율법을 주야로 묵상하는도다.",
    weight: 65,
  },
  {
    referenceKo: "시편 119:105",
    bookAbbrEn: "PSA",
    chapter: 119,
    verseStart: 105,
    themes: ["말씀", "인도하심"],
    situationTags: ["말씀묵상회복"],
    emotionTags: [],
    summary: "주의 말씀은 내 발에 등이요 내 길에 빛이니이다.",
    weight: 60,
  },
  {
    referenceKo: "누가복음 18:1",
    bookAbbrEn: "LUK",
    chapter: 18,
    verseStart: 1,
    themes: ["기도"],
    situationTags: ["기도결단"],
    emotionTags: [],
    summary: "항상 기도하고 낙심하지 말아야 할 것을 비유로.",
    weight: 55,
  },
  {
    referenceKo: "야고보서 5:13",
    bookAbbrEn: "JAS",
    chapter: 5,
    verseStart: 13,
    themes: ["기도"],
    situationTags: ["기도결단"],
    emotionTags: [],
    summary: "너희 중에 고난 당하는 자가 있느냐 그는 기도할 것이요.",
    weight: 55,
  },

  // ─── 공동체 / 일터 / 섬김 ─────────────────────────────────────
  {
    referenceKo: "갈라디아서 6:2",
    bookAbbrEn: "GAL",
    chapter: 6,
    verseStart: 2,
    themes: ["공동체", "섬김"],
    situationTags: ["공동체"],
    emotionTags: [],
    summary: "너희가 짐을 서로 지라.",
    weight: 55,
  },
  {
    referenceKo: "빌립보서 2:3-4",
    bookAbbrEn: "PHP",
    chapter: 2,
    verseStart: 3,
    verseEnd: 4,
    themes: ["겸손", "섬김"],
    situationTags: ["대인관계", "공동체"],
    emotionTags: [],
    summary: "겸손한 마음으로 각각 자기보다 남을 낫게 여기고.",
    weight: 55,
  },
  {
    referenceKo: "에베소서 6:7-8",
    bookAbbrEn: "EPH",
    chapter: 6,
    verseStart: 7,
    verseEnd: 8,
    themes: ["일", "성실"],
    situationTags: ["일의의미", "회사어려움"],
    emotionTags: [],
    summary: "기쁜 마음으로 섬기기를 주께 하듯 하고.",
    weight: 65,
  },

  // ─── 자존감 / 정체성 ───────────────────────────────────────────
  {
    referenceKo: "시편 139:13-14",
    bookAbbrEn: "PSA",
    chapter: 139,
    verseStart: 13,
    verseEnd: 14,
    themes: ["정체성"],
    situationTags: [],
    emotionTags: ["우울", "자책"],
    summary: "나를 지으심이 심히 기묘하심이라.",
    weight: 60,
  },
  {
    referenceKo: "이사야 43:1",
    bookAbbrEn: "ISA",
    chapter: 43,
    verseStart: 1,
    themes: ["정체성", "함께하심"],
    situationTags: [],
    emotionTags: ["두려움"],
    summary: "내가 너를 지명하여 불렀나니 너는 내 것이라.",
    weight: 65,
  },

  // ─── 시험 / 유혹 ───────────────────────────────────────────────
  {
    referenceKo: "고린도전서 10:13",
    bookAbbrEn: "1CO",
    chapter: 10,
    verseStart: 13,
    themes: ["시험", "피할길"],
    situationTags: ["유혹"],
    emotionTags: [],
    summary: "감당하지 못할 시험 당함을 허락지 아니하시고.",
    weight: 60,
  },
  {
    referenceKo: "야고보서 1:2-4",
    bookAbbrEn: "JAS",
    chapter: 1,
    verseStart: 2,
    verseEnd: 4,
    themes: ["시험", "인내"],
    situationTags: ["시련"],
    emotionTags: ["답답함"],
    summary: "너희가 여러 가지 시험을 당하거든 온전히 기쁘게 여기라.",
    weight: 60,
  },

  // ─── 절제 / 자기관리 ───────────────────────────────────────────
  {
    referenceKo: "잠언 25:28",
    bookAbbrEn: "PRO",
    chapter: 25,
    verseStart: 28,
    themes: ["절제"],
    situationTags: ["자기관리"],
    emotionTags: [],
    summary: "마음을 제어하지 아니하는 자는 성읍이 무너진 것 같으니라.",
    weight: 55,
  },
  {
    referenceKo: "고린도전서 9:24-27",
    bookAbbrEn: "1CO",
    chapter: 9,
    verseStart: 24,
    verseEnd: 27,
    themes: ["절제", "훈련"],
    situationTags: ["자기관리"],
    emotionTags: [],
    summary: "이기기를 다투는 자마다 모든 일에 절제하나니.",
    weight: 55,
  },

  // ─── 하나님의 긍휼 / 자비 ─────────────────────────────────────
  {
    referenceKo: "시편 103:13-14",
    bookAbbrEn: "PSA",
    chapter: 103,
    verseStart: 13,
    verseEnd: 14,
    themes: ["긍휼"],
    situationTags: [],
    emotionTags: ["자책"],
    summary: "아버지가 자식을 긍휼히 여김 같이.",
    weight: 55,
  },
  {
    referenceKo: "미가 7:18-19",
    bookAbbrEn: "MIC",
    chapter: 7,
    verseStart: 18,
    verseEnd: 19,
    themes: ["긍휼", "용서"],
    situationTags: [],
    emotionTags: ["죄책감"],
    summary: "주와 같은 신이 어디 있으리이까.",
    weight: 50,
  },

  // ─── 소망 / 부활 ───────────────────────────────────────────────
  {
    referenceKo: "로마서 5:3-5",
    bookAbbrEn: "ROM",
    chapter: 5,
    verseStart: 3,
    verseEnd: 5,
    themes: ["인내", "소망"],
    situationTags: ["시련"],
    emotionTags: ["답답함"],
    summary: "환난은 인내를 인내는 연단을 연단은 소망을 이루는 줄.",
    weight: 60,
  },
  {
    referenceKo: "고린도후서 4:16-18",
    bookAbbrEn: "2CO",
    chapter: 4,
    verseStart: 16,
    verseEnd: 18,
    themes: ["소망", "인내"],
    situationTags: ["지침"],
    emotionTags: ["무기력"],
    summary: "겉사람은 낡아지나 속사람은 날로 새로워지도다.",
    weight: 60,
  },
  {
    referenceKo: "히브리서 4:15-16",
    bookAbbrEn: "HEB",
    chapter: 4,
    verseStart: 15,
    verseEnd: 16,
    themes: ["위로", "기도"],
    situationTags: ["기도결단"],
    emotionTags: ["외로움"],
    summary: "긍휼하심을 받고 때를 따라 돕는 은혜를 얻기 위하여.",
    weight: 60,
  },

  // ─── 찬양 / 예배 ───────────────────────────────────────────────
  {
    referenceKo: "시편 95:6-7",
    bookAbbrEn: "PSA",
    chapter: 95,
    verseStart: 6,
    verseEnd: 7,
    themes: ["예배"],
    situationTags: ["예배회복"],
    emotionTags: [],
    summary: "오라 우리가 굽혀 경배하며.",
    weight: 50,
  },
  {
    referenceKo: "시편 100:1-5",
    bookAbbrEn: "PSA",
    chapter: 100,
    verseStart: 1,
    verseEnd: 5,
    themes: ["감사", "예배"],
    situationTags: ["예배회복"],
    emotionTags: [],
    summary: "감사함으로 그 문에 들어가며 찬송함으로 그 궁정에 들어가서.",
    weight: 50,
  },

  // ─── 자기방임을 깨는 작은 책임 ────────────────────────────────
  {
    referenceKo: "누가복음 16:10",
    bookAbbrEn: "LUK",
    chapter: 16,
    verseStart: 10,
    themes: ["성실", "작은책임"],
    situationTags: ["작은책임회복", "자기방임"],
    emotionTags: [],
    summary: "지극히 작은 것에 충성된 자는 큰 것에도 충성되고.",
    weight: 75,
  },
  {
    referenceKo: "잠언 12:24",
    bookAbbrEn: "PRO",
    chapter: 12,
    verseStart: 24,
    themes: ["성실"],
    situationTags: ["자기방임"],
    emotionTags: [],
    summary: "부지런한 자의 손은 사람을 다스리게 되어도.",
    weight: 60,
  },

  // ─── 공포/압도/긴급한 순간 ────────────────────────────────────
  {
    referenceKo: "시편 46:10",
    bookAbbrEn: "PSA",
    chapter: 46,
    verseStart: 10,
    themes: ["잠잠함"],
    situationTags: ["삶의흔들림"],
    emotionTags: ["불안"],
    summary: "너희는 가만히 있어 내가 하나님 됨을 알지어다.",
    weight: 65,
  },
  {
    referenceKo: "시편 62:5-8",
    bookAbbrEn: "PSA",
    chapter: 62,
    verseStart: 5,
    verseEnd: 8,
    themes: ["잠잠함", "피난처"],
    situationTags: ["삶의흔들림"],
    emotionTags: ["불안", "답답함"],
    summary: "나의 영혼아 잠잠히 하나님만 바라라.",
    weight: 70,
  },

  // ─── 성령/도우심 ───────────────────────────────────────────────
  {
    referenceKo: "로마서 8:26-27",
    bookAbbrEn: "ROM",
    chapter: 8,
    verseStart: 26,
    verseEnd: 27,
    themes: ["도우심", "기도"],
    situationTags: ["기도결단"],
    emotionTags: ["답답함"],
    summary: "성령이 친히 말할 수 없는 탄식으로 우리를 위하여 간구하시느니라.",
    weight: 70,
  },
  {
    referenceKo: "사도행전 1:8",
    bookAbbrEn: "ACT",
    chapter: 1,
    verseStart: 8,
    themes: ["성령", "사명"],
    situationTags: [],
    emotionTags: [],
    summary: "성령이 너희에게 임하시면 권능을 받고.",
    weight: 45,
  },

  // ─── 가족/부모/자녀 ───────────────────────────────────────────
  {
    referenceKo: "여호수아 24:15",
    bookAbbrEn: "JOS",
    chapter: 24,
    verseStart: 15,
    themes: ["결단", "가정"],
    situationTags: ["가정"],
    emotionTags: [],
    summary: "오직 나와 내 집은 여호와를 섬기겠노라.",
    weight: 50,
  },
  {
    referenceKo: "신명기 6:5-7",
    bookAbbrEn: "DEU",
    chapter: 6,
    verseStart: 5,
    verseEnd: 7,
    themes: ["가정", "신앙계승"],
    situationTags: ["가정"],
    emotionTags: [],
    summary: "네 마음을 다하고 성품을 다하고 힘을 다하여 사랑하라.",
    weight: 45,
  },

  // ─── 감정: 답답함/풀리지 않는 문제 ────────────────────────────
  {
    referenceKo: "시편 142:1-3",
    bookAbbrEn: "PSA",
    chapter: 142,
    verseStart: 1,
    verseEnd: 3,
    themes: ["토로", "기도"],
    situationTags: ["기도결단"],
    emotionTags: ["답답함", "외로움"],
    summary: "내 심령이 속에서 상할 때에 주께서 내 길을 아셨나이다.",
    weight: 70,
  },
  {
    referenceKo: "시편 13:1-6",
    bookAbbrEn: "PSA",
    chapter: 13,
    verseStart: 1,
    verseEnd: 6,
    themes: ["토로", "신뢰"],
    situationTags: [],
    emotionTags: ["슬픔", "답답함"],
    summary: "여호와여 어느 때까지니이까 나를 영원히 잊으시나이까.",
    weight: 55,
  },
];

async function main() {
  console.log(`[seed-verses] 총 ${SEEDS.length}개 구절 시드 시작`);

  for (const s of SEEDS) {
    await db
      .insert(verses)
      .values({
        referenceKo: s.referenceKo,
        bookAbbrEn: s.bookAbbrEn,
        chapter: s.chapter,
        verseStart: s.verseStart,
        verseEnd: s.verseEnd ?? null,
        deepLinkUrl: link(s.bookAbbrEn, s.chapter, s.verseStart),
        themes: s.themes,
        situationTags: s.situationTags,
        emotionTags: s.emotionTags,
        summary: s.summary ?? null,
        weight: s.weight ?? 0,
        isGeneric: s.isGeneric ?? false,
      })
      .onConflictDoUpdate({
        target: [verses.bookAbbrEn, verses.chapter, verses.verseStart, verses.verseEnd],
        set: {
          referenceKo: s.referenceKo,
          deepLinkUrl: link(s.bookAbbrEn, s.chapter, s.verseStart),
          themes: s.themes,
          situationTags: s.situationTags,
          emotionTags: s.emotionTags,
          summary: s.summary ?? null,
          weight: s.weight ?? 0,
          isGeneric: s.isGeneric ?? false,
        },
      });
  }

  const [{ count }] = await db.execute<{ count: number }>(
    sql`select count(*)::int as count from verse`
  );
  console.log(`[seed-verses] 완료. verse 테이블 row=${count}`);
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
